#!/bin/bash

### BEGIN INIT INFO
# Provides:          mhhc
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start mhhc sync at startup
# Description:       MHH Sync script daemon
### END INIT INFO

# MHH sync control
########### SETTINGS ##########

## the user that must be used to run the bot
USER=root

## where mhh_sync.sh is located
MHH_BIN="/var/www/emoncms/Modules/mhh/mhh_sync.sh"

## where the binary is located
MHH_EXEC=/bin/bash

########### SETTINGS END ############

set -e
DEBUG=off
MHH_PID_FILE="/run/mhhc.pid"

if [ ! -f "$MHH_BIN" ]; then
 echo "ERROR: file not found : '$MHH_BIN'"
 exit 1
fi
if [ ! -x "$MHH_BIN" ]; then
 echo "ERROR: cannot execute '$MHH_BIN'"
 exit 1
fi
if [ ! -f "$MHH_EXEC" ]; then
 echo "ERROR: file not found : '$MHH_EXEC'"
 exit 1
fi
if [ ! -x "$MHH_EXEC" ]; then
 echo "ERROR: cannot execute '$MHH_EXEC'"
 exit 1
fi

if [ "$(whoami)" != "$USER" ]; then
	echo "ERROR: you have to run that script as $USER"
	exit 1
fi


function debug() {
	if [ "$DEBUG" = "on" ]; then
		echo DEBUG: $@
	fi
}


function do_start {
	cd $(dirname $MHH_BIN)
	$MHH_EXEC $MHH_BIN &
	echo $! > $MHH_PID_FILE
}

function do_stop {
	NB_PROCESS=`ps ax | grep mhh_sync.sh | grep -v grep | wc -l`
	if [ $NB_PROCESS -gt 1 ]; then
		echo "ERROR: multiple mhh_sync processes found, you'd better kill thoses processes by hand."
	elif [ $NB_PROCESS -eq 1 ]; then
		if [ -f $MHH_PID_FILE ]; then
			PID=$(cat $MHH_PID_FILE)
			NB_PROCESS=`ps hax $PID | grep mhh_sync.sh | grep -v grep | wc -l`
			if [ $NB_PROCESS -eq 1 ]; then
				kill -15 $PID
			else
				echo "ERROR: process $PID does not seem to be mhh_sync"
				echo "kill mhh_sync by hand"
			fi
		fi
	else
		echo "WARNING: are you sure mhh_sync is running ?"
	fi
}


kill_script() {
 PID=`ps hax | grep "mhh_sync.sh" | grep -v grep | cut -d' ' -f1 | head -n1`
 echo "killing process [$PID]"
 kill -9 $PID
}


case "$1" in
	start)
		echo "Starting MHH Sync"
		NB_PROCESS=`ps ax | grep mhh_sync.sh | grep -v grep | wc -l`
		if [ $NB_PROCESS -eq 0 ]; then
			do_start
		else
			echo "ERROR: mhh_sync is already running"
		fi
	;;
	stop)
		echo -n "Stopping MHH Sync: "
		do_stop
		echo "stopped"
	;;

	restart)
 		echo -n "Restarting MHH Sync"
		do_stop
		sleep 1
		do_start
	;;
	
	status)
		debug "status:"
		NB_PROCESS=`ps ax | grep mhh_sync.sh | grep -v grep | wc -l`
		debug "NB_PROCESS: $NB_PROCESS"
		if [ $NB_PROCESS -gt 1 ]; then
			echo "WARNING: multiple mhh_sync processes found !"
		elif [ $NB_PROCESS -eq 1 ]; then
			echo "running"
		else
			echo "stopped"
		fi
	;;

	kill)
		kill_script
	;;
 *)
	PROG_NAME=`basename $0`
	echo "Usage: $PROG_NAME {start|stop|restart|status|kill}"
	exit 1
esac

exit 0
